# Jekyll configuration for GitHub Pages
title: Statistical Knowledge Base
description: A comprehensive collection of statistical concepts, hypothesis testing methods, and probability distributions
author: Oliver Lei

# Theme settings
theme: jekyll-theme-cayman

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Navigation
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - .github
  - .gitignore
  - README.md
  - paper-reading-notes/machine-learning/attention-is-all-you-need.md
  - paper-reading-notes/machine-learning/gpt-3-in-context-learning.md
  - paper-reading-notes/machine-learning/tabpfn-learning-path.md
  - paper-reading-notes/machine-learning/tabpfn-mathematical-analysis.md
  - paper-reading-notes/statistical-methods
  - experimentations
